// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UnitTestProject1
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("查詢訂單")]
    public partial class 查詢訂單Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "查詢Order.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "查詢訂單", "身為採購人員，我需要知道有哪些訂單，以利後續作業。", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("我在訂單作業查詢訂單資料")]
        public virtual void 我在訂單作業查詢訂單資料()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("我在訂單作業查詢訂單資料", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "CustomerID",
                        "OrderDate"});
            table1.AddRow(new string[] {
                        "VINET",
                        ""});
#line 12
 testRunner.Given("查詢條件", ((string)(null)), table1, "Given ");
#line 15
 testRunner.When("我調用GetOrders", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "OrderID",
                        "CustomerID",
                        "EmployeeID",
                        "OrderDate",
                        "RequiredDate",
                        "ProductID",
                        "UnitPrice",
                        "Quantity",
                        "Discount"});
            table2.AddRow(new string[] {
                        "10248",
                        "VINET",
                        "5",
                        "1996-07-04 00:00:00.000",
                        "1996-08-01 00:00:00.000",
                        "11",
                        "14.00",
                        "12",
                        "0"});
            table2.AddRow(new string[] {
                        "10248",
                        "VINET",
                        "5",
                        "1996-07-04 00:00:00.000",
                        "1996-08-01 00:00:00.000",
                        "42",
                        "9.80",
                        "10",
                        "0"});
            table2.AddRow(new string[] {
                        "10248",
                        "VINET",
                        "5",
                        "1996-07-04 00:00:00.000",
                        "1996-08-01 00:00:00.000",
                        "72",
                        "34.80",
                        "5",
                        "0"});
            table2.AddRow(new string[] {
                        "10274",
                        "VINET",
                        "6",
                        "1996-08-06 00:00:00.000",
                        "1996-09-03 00:00:00.000",
                        "71",
                        "17.20",
                        "20",
                        "0"});
            table2.AddRow(new string[] {
                        "10274",
                        "VINET",
                        "6",
                        "1996-08-06 00:00:00.000",
                        "1996-09-03 00:00:00.000",
                        "72",
                        "27.80",
                        "7",
                        "0"});
            table2.AddRow(new string[] {
                        "10295",
                        "VINET",
                        "2",
                        "1996-09-02 00:00:00.000",
                        "1996-09-30 00:00:00.000",
                        "56",
                        "30.40",
                        "4",
                        "0"});
            table2.AddRow(new string[] {
                        "10737",
                        "VINET",
                        "2",
                        "1997-11-11 00:00:00.000",
                        "1997-12-09 00:00:00.000",
                        "13",
                        "6.00",
                        "4",
                        "0"});
            table2.AddRow(new string[] {
                        "10737",
                        "VINET",
                        "2",
                        "1997-11-11 00:00:00.000",
                        "1997-12-09 00:00:00.000",
                        "41",
                        "9.65",
                        "12",
                        "0"});
            table2.AddRow(new string[] {
                        "10739",
                        "VINET",
                        "3",
                        "1997-11-12 00:00:00.000",
                        "1997-12-10 00:00:00.000",
                        "36",
                        "19.00",
                        "6",
                        "0"});
            table2.AddRow(new string[] {
                        "10739",
                        "VINET",
                        "3",
                        "1997-11-12 00:00:00.000",
                        "1997-12-10 00:00:00.000",
                        "52",
                        "7.00",
                        "18",
                        "0"});
#line 16
 testRunner.Then("我會得到訂單資料如下", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
